---
apiVersion: v1
kind: Pod
metadata:
  name: boutique-firmware-kaniko-builder
  namespace: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--context=git://github.com//thecase/boutique-firmware.git",
             "--destination=thecase/boutique-firmware:1.0.2",
             "--dockerfile=Dockerfile"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-registry
        items:
          - key: .dockerconfigjson
            path: config.json


# for info about building from a private repo:
# https://medium.com/hiredscore-engineering/kaniko-builds-with-private-repository-634d5e7fa4a5
